---
all:
  children:
    firephenix:
      hosts:
        firephenix-host:
          ansible_host: "firephenix.de"
          ansible_user: root
          ansible_ssh_private_key_file: "~/.ssh/firephenix_dev_vm"
