---
- name: Install unattended-upgrades packages
  ansible.builtin.apt:
    name:
      - unattended-upgrades
      - apt-listchanges
    state: present
  when: auto_updates_enable | bool

- name: Configure unattended-upgrades
  ansible.builtin.copy:
    dest: /etc/apt/apt.conf.d/50unattended-upgrades
    mode: "0644"
    content: |
      Unattended-Upgrade::Origins-Pattern {
          "origin=Debian,codename=${distro_codename},label=Debian";
          "origin=Debian,codename=${distro_codename},label=Debian-Security";
          "origin=Debian,codename=${distro_codename}-security,label=Debian-Security";
      };

      Unattended-Upgrade::AutoFixInterruptedDpkg "true";
      Unattended-Upgrade::MinimalSteps "true";
      Unattended-Upgrade::Remove-Unused-Kernel-Packages "true";
      Unattended-Upgrade::Remove-New-Unused-Dependencies "true";
      Unattended-Upgrade::Remove-Unused-Dependencies "true";
      Unattended-Upgrade::Automatic-Reboot "{{ 'true' if auto_updates_automatic_reboot else 'false' }}";
      Unattended-Upgrade::SyslogEnable "true";
  when: auto_updates_enable | bool

- name: Configure periodic apt jobs
  ansible.builtin.copy:
    dest: /etc/apt/apt.conf.d/20auto-upgrades
    mode: "0644"
    content: |
      APT::Periodic::Update-Package-Lists "1";
      APT::Periodic::Unattended-Upgrade "1";
      APT::Periodic::Download-Upgradeable-Packages "1";
      APT::Periodic::AutocleanInterval "7";
  when: auto_updates_enable | bool

- name: Enable unattended-upgrades
  ansible.builtin.systemd:
    name: unattended-upgrades
    state: started
    enabled: true
  when: auto_updates_enable | bool

